name: Deploy to Personal Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Simulation Repo
        uses: actions/checkout@v3
        with:
          repository: sachd-vipu/queuesimulation
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Checkout Website Repo
        uses: actions/checkout@v3
        with:
          repository: sachd-vipu/vipulsachdeva.tech
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: website

      - name: Deploy to Website
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          mkdir -p website/projects/queuesimulation
          cp -r dist/* website/projects/queuesimulation/
          cd website
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add projects/queuesimulation
          git commit -m "Update queue simulation project"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/sachd-vipu/vipulsachdeva.tech.git main 